inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - "bin/*"
    - "vendor/bundle/**/*"
    - "storage/**/*"
    - "tmp/**/*"

Layout/EmptyLinesAroundBlockBody:
  Enabled: true
  Exclude:
    - "db/schema.rb"

Naming/PredicateMethod:
  AllowedMethods:
    - call
    - save

Style/NumericLiterals:
  Enabled: true
  Exclude:
    - "db/schema.rb"

Style/SafeNavigation:
  Enabled: false

RSpec/ContextWording:
  Prefixes:
    - when
    - with
    - and

RSpec/MultipleExpectations:
  Max: 20

RSpec/MultipleMemoizedHelpers:
  Max: 20

RSpec/NestedGroups:
  Max: 8

RSpec/VerifiedDoubles:
  IgnoreNameless: true
  IgnoreSymbolicNames: true
