services:
  db:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Ee56KRC39xzcVUiA
      - POSTGRES_DB=postgres
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

  web:
    image: southwark-bsp/ruby
    build: .
    stdin_open: true
    tty: true
    init: true
    environment:
      DATABASE_URL: postgres://postgres:Ee56KRC39xzcVUiA@db:5432
      DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL: "true"
      PIDFILE: "/tmp/pids/server.pid"
    command: ["foreman", "start", "-f", "Procfile.dev"]
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - .:/app
      - bundle:/bundle
      - node_modules:/app/node_modules
    tmpfs:
      - /tmp/pids/
    depends_on:
      - db

volumes:
  bundle:
  db:
  node_modules:
