version: 2.1
orbs:
  ruby: circleci/ruby@1.1.2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.2-node-browsers 
        environment:
          RAILS_ENV: test
          BUNDLE_JOBS: 4
          BUNDLE_RETRY: 3
          PGUSER: postgres
          PGHOST: 127.0.0.1
      - image: circleci/postgres:13-postgis-ram
        environment:
          POSTGRES_USER: postgres
          POSTGRES_HOST_AUTH_METHOD: trust

    steps:
      - checkout

      # Restore cache
      - restore_cache:
          keys:
            - gems-{{ checksum "Gemfile.lock" }}
            - gems- # used if checksum fails

      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
            - yarn-packages- # used if checksum fails

      # Bundle install dependencies
      - run:
          name: Install gems
          command: bundle install --path vendor/bundle

      # Store bundle cache
      - save_cache:
          key: gems-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      # Yarn install dependencies
      - run:
          name: Install javascripts
          command: yarn install 

      # Store yarn cache
      - save_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run:
          name: Database Setup
          command: |
            bundle exec rake db:create db:schema:load --trace

      - run:
          name: Rubocop
          command: bundle exec rubocop

      - run:
          name: RSpec
          command: bundle exec rspec

      - run:
          name: Cucumber
          command: bundle exec cucumber
